/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FleetInfo
 */
public class FleetInfoTest {
    private final FleetInfo model = new FleetInfo();

    /**
     * Model tests for FleetInfo
     */
    @Test
    public void testFleetInfo() {
        // TODO: test FleetInfo
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'eveKitVersion'
     */
    @Test
    public void eveKitVersionTest() {
        // TODO: test eveKitVersion
    }

    /**
     * Test the property 'lifeStart'
     */
    @Test
    public void lifeStartTest() {
        // TODO: test lifeStart
    }

    /**
     * Test the property 'lifeEnd'
     */
    @Test
    public void lifeEndTest() {
        // TODO: test lifeEnd
    }

    /**
     * Test the property 'fleetID'
     */
    @Test
    public void fleetIDTest() {
        // TODO: test fleetID
    }

    /**
     * Test the property 'motd'
     */
    @Test
    public void motdTest() {
        // TODO: test motd
    }

    /**
     * Test the property 'freeMove'
     */
    @Test
    public void freeMoveTest() {
        // TODO: test freeMove
    }

    /**
     * Test the property 'voiceEnabled'
     */
    @Test
    public void voiceEnabledTest() {
        // TODO: test voiceEnabled
    }

    /**
     * Test the property 'registered'
     */
    @Test
    public void registeredTest() {
        // TODO: test registered
    }

    /**
     * Test the property 'lifeStartDate'
     */
    @Test
    public void lifeStartDateTest() {
        // TODO: test lifeStartDate
    }

    /**
     * Test the property 'lifeEndDate'
     */
    @Test
    public void lifeEndDateTest() {
        // TODO: test lifeEndDate
    }

}
