/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlanetaryRoute
 */
public class PlanetaryRouteTest {
    private final PlanetaryRoute model = new PlanetaryRoute();

    /**
     * Model tests for PlanetaryRoute
     */
    @Test
    public void testPlanetaryRoute() {
        // TODO: test PlanetaryRoute
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'eveKitVersion'
     */
    @Test
    public void eveKitVersionTest() {
        // TODO: test eveKitVersion
    }

    /**
     * Test the property 'lifeStart'
     */
    @Test
    public void lifeStartTest() {
        // TODO: test lifeStart
    }

    /**
     * Test the property 'lifeEnd'
     */
    @Test
    public void lifeEndTest() {
        // TODO: test lifeEnd
    }

    /**
     * Test the property 'planetID'
     */
    @Test
    public void planetIDTest() {
        // TODO: test planetID
    }

    /**
     * Test the property 'routeID'
     */
    @Test
    public void routeIDTest() {
        // TODO: test routeID
    }

    /**
     * Test the property 'sourcePinID'
     */
    @Test
    public void sourcePinIDTest() {
        // TODO: test sourcePinID
    }

    /**
     * Test the property 'destinationPinID'
     */
    @Test
    public void destinationPinIDTest() {
        // TODO: test destinationPinID
    }

    /**
     * Test the property 'contentTypeID'
     */
    @Test
    public void contentTypeIDTest() {
        // TODO: test contentTypeID
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'waypoints'
     */
    @Test
    public void waypointsTest() {
        // TODO: test waypoints
    }

    /**
     * Test the property 'lifeStartDate'
     */
    @Test
    public void lifeStartDateTest() {
        // TODO: test lifeStartDate
    }

    /**
     * Test the property 'lifeEndDate'
     */
    @Test
    public void lifeEndDateTest() {
        // TODO: test lifeEndDate
    }

}
