/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ResearchAgent
 */
public class ResearchAgentTest {
    private final ResearchAgent model = new ResearchAgent();

    /**
     * Model tests for ResearchAgent
     */
    @Test
    public void testResearchAgent() {
        // TODO: test ResearchAgent
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'eveKitVersion'
     */
    @Test
    public void eveKitVersionTest() {
        // TODO: test eveKitVersion
    }

    /**
     * Test the property 'lifeStart'
     */
    @Test
    public void lifeStartTest() {
        // TODO: test lifeStart
    }

    /**
     * Test the property 'lifeEnd'
     */
    @Test
    public void lifeEndTest() {
        // TODO: test lifeEnd
    }

    /**
     * Test the property 'agentID'
     */
    @Test
    public void agentIDTest() {
        // TODO: test agentID
    }

    /**
     * Test the property 'pointsPerDay'
     */
    @Test
    public void pointsPerDayTest() {
        // TODO: test pointsPerDay
    }

    /**
     * Test the property 'remainderPoints'
     */
    @Test
    public void remainderPointsTest() {
        // TODO: test remainderPoints
    }

    /**
     * Test the property 'researchStartDate'
     */
    @Test
    public void researchStartDateTest() {
        // TODO: test researchStartDate
    }

    /**
     * Test the property 'skillTypeID'
     */
    @Test
    public void skillTypeIDTest() {
        // TODO: test skillTypeID
    }

    /**
     * Test the property 'lifeStartDate'
     */
    @Test
    public void lifeStartDateTest() {
        // TODO: test lifeStartDate
    }

    /**
     * Test the property 'lifeEndDate'
     */
    @Test
    public void lifeEndDateTest() {
        // TODO: test lifeEndDate
    }

    /**
     * Test the property 'researchStartDateDate'
     */
    @Test
    public void researchStartDateDateTest() {
        // TODO: test researchStartDateDate
    }

}
