/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SkillInQueue
 */
public class SkillInQueueTest {
    private final SkillInQueue model = new SkillInQueue();

    /**
     * Model tests for SkillInQueue
     */
    @Test
    public void testSkillInQueue() {
        // TODO: test SkillInQueue
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'eveKitVersion'
     */
    @Test
    public void eveKitVersionTest() {
        // TODO: test eveKitVersion
    }

    /**
     * Test the property 'lifeStart'
     */
    @Test
    public void lifeStartTest() {
        // TODO: test lifeStart
    }

    /**
     * Test the property 'lifeEnd'
     */
    @Test
    public void lifeEndTest() {
        // TODO: test lifeEnd
    }

    /**
     * Test the property 'endSP'
     */
    @Test
    public void endSPTest() {
        // TODO: test endSP
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'queuePosition'
     */
    @Test
    public void queuePositionTest() {
        // TODO: test queuePosition
    }

    /**
     * Test the property 'startSP'
     */
    @Test
    public void startSPTest() {
        // TODO: test startSP
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'typeID'
     */
    @Test
    public void typeIDTest() {
        // TODO: test typeID
    }

    /**
     * Test the property 'trainingStartSP'
     */
    @Test
    public void trainingStartSPTest() {
        // TODO: test trainingStartSP
    }

    /**
     * Test the property 'lifeStartDate'
     */
    @Test
    public void lifeStartDateTest() {
        // TODO: test lifeStartDate
    }

    /**
     * Test the property 'lifeEndDate'
     */
    @Test
    public void lifeEndDateTest() {
        // TODO: test lifeEndDate
    }

    /**
     * Test the property 'endTimeDate'
     */
    @Test
    public void endTimeDateTest() {
        // TODO: test endTimeDate
    }

    /**
     * Test the property 'startTimeDate'
     */
    @Test
    public void startTimeDateTest() {
        // TODO: test startTimeDate
    }

}
