/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class CharacterSheet implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private Long cid;

  public static final String SERIALIZED_NAME_EVE_KIT_VERSION = "eveKitVersion";
  @SerializedName(SERIALIZED_NAME_EVE_KIT_VERSION)
  private Integer eveKitVersion;

  public static final String SERIALIZED_NAME_LIFE_START = "lifeStart";
  @SerializedName(SERIALIZED_NAME_LIFE_START)
  private Long lifeStart;

  public static final String SERIALIZED_NAME_LIFE_END = "lifeEnd";
  @SerializedName(SERIALIZED_NAME_LIFE_END)
  private Long lifeEnd;

  public static final String SERIALIZED_NAME_CHARACTER_I_D = "characterID";
  @SerializedName(SERIALIZED_NAME_CHARACTER_I_D)
  private Long characterID;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CORPORATION_I_D = "corporationID";
  @SerializedName(SERIALIZED_NAME_CORPORATION_I_D)
  private Integer corporationID;

  public static final String SERIALIZED_NAME_RACE_I_D = "raceID";
  @SerializedName(SERIALIZED_NAME_RACE_I_D)
  private Integer raceID;

  public static final String SERIALIZED_NAME_DO_B = "doB";
  @SerializedName(SERIALIZED_NAME_DO_B)
  private Long doB;

  public static final String SERIALIZED_NAME_BLOODLINE_I_D = "bloodlineID";
  @SerializedName(SERIALIZED_NAME_BLOODLINE_I_D)
  private Integer bloodlineID;

  public static final String SERIALIZED_NAME_ANCESTRY_I_D = "ancestryID";
  @SerializedName(SERIALIZED_NAME_ANCESTRY_I_D)
  private Integer ancestryID;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private String gender;

  public static final String SERIALIZED_NAME_ALLIANCE_I_D = "allianceID";
  @SerializedName(SERIALIZED_NAME_ALLIANCE_I_D)
  private Integer allianceID;

  public static final String SERIALIZED_NAME_FACTION_I_D = "factionID";
  @SerializedName(SERIALIZED_NAME_FACTION_I_D)
  private Integer factionID;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_SECURITY_STATUS = "securityStatus";
  @SerializedName(SERIALIZED_NAME_SECURITY_STATUS)
  private Float securityStatus;

  public static final String SERIALIZED_NAME_LIFE_START_DATE = "lifeStartDate";
  @SerializedName(SERIALIZED_NAME_LIFE_START_DATE)
  private OffsetDateTime lifeStartDate;

  public static final String SERIALIZED_NAME_LIFE_END_DATE = "lifeEndDate";
  @SerializedName(SERIALIZED_NAME_LIFE_END_DATE)
  private OffsetDateTime lifeEndDate;

  public static final String SERIALIZED_NAME_DO_B_DATE = "doBDate";
  @SerializedName(SERIALIZED_NAME_DO_B_DATE)
  private OffsetDateTime doBDate;

  public CharacterSheet cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public CharacterSheet eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public CharacterSheet lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public CharacterSheet lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public CharacterSheet characterID(Long characterID) {
    this.characterID = characterID;
    return this;
  }

   /**
   * Get characterID
   * @return characterID
  **/
  @ApiModelProperty(value = "")
  public Long getCharacterID() {
    return characterID;
  }

  public void setCharacterID(Long characterID) {
    this.characterID = characterID;
  }

  public CharacterSheet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CharacterSheet corporationID(Integer corporationID) {
    this.corporationID = corporationID;
    return this;
  }

   /**
   * Get corporationID
   * @return corporationID
  **/
  @ApiModelProperty(value = "")
  public Integer getCorporationID() {
    return corporationID;
  }

  public void setCorporationID(Integer corporationID) {
    this.corporationID = corporationID;
  }

  public CharacterSheet raceID(Integer raceID) {
    this.raceID = raceID;
    return this;
  }

   /**
   * Get raceID
   * @return raceID
  **/
  @ApiModelProperty(value = "")
  public Integer getRaceID() {
    return raceID;
  }

  public void setRaceID(Integer raceID) {
    this.raceID = raceID;
  }

  public CharacterSheet doB(Long doB) {
    this.doB = doB;
    return this;
  }

   /**
   * Get doB
   * @return doB
  **/
  @ApiModelProperty(value = "")
  public Long getDoB() {
    return doB;
  }

  public void setDoB(Long doB) {
    this.doB = doB;
  }

  public CharacterSheet bloodlineID(Integer bloodlineID) {
    this.bloodlineID = bloodlineID;
    return this;
  }

   /**
   * Get bloodlineID
   * @return bloodlineID
  **/
  @ApiModelProperty(value = "")
  public Integer getBloodlineID() {
    return bloodlineID;
  }

  public void setBloodlineID(Integer bloodlineID) {
    this.bloodlineID = bloodlineID;
  }

  public CharacterSheet ancestryID(Integer ancestryID) {
    this.ancestryID = ancestryID;
    return this;
  }

   /**
   * Get ancestryID
   * @return ancestryID
  **/
  @ApiModelProperty(value = "")
  public Integer getAncestryID() {
    return ancestryID;
  }

  public void setAncestryID(Integer ancestryID) {
    this.ancestryID = ancestryID;
  }

  public CharacterSheet gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public CharacterSheet allianceID(Integer allianceID) {
    this.allianceID = allianceID;
    return this;
  }

   /**
   * Get allianceID
   * @return allianceID
  **/
  @ApiModelProperty(value = "")
  public Integer getAllianceID() {
    return allianceID;
  }

  public void setAllianceID(Integer allianceID) {
    this.allianceID = allianceID;
  }

  public CharacterSheet factionID(Integer factionID) {
    this.factionID = factionID;
    return this;
  }

   /**
   * Get factionID
   * @return factionID
  **/
  @ApiModelProperty(value = "")
  public Integer getFactionID() {
    return factionID;
  }

  public void setFactionID(Integer factionID) {
    this.factionID = factionID;
  }

  public CharacterSheet description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CharacterSheet securityStatus(Float securityStatus) {
    this.securityStatus = securityStatus;
    return this;
  }

   /**
   * Get securityStatus
   * @return securityStatus
  **/
  @ApiModelProperty(value = "")
  public Float getSecurityStatus() {
    return securityStatus;
  }

  public void setSecurityStatus(Float securityStatus) {
    this.securityStatus = securityStatus;
  }

  public CharacterSheet lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public CharacterSheet lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }

  public CharacterSheet doBDate(OffsetDateTime doBDate) {
    this.doBDate = doBDate;
    return this;
  }

   /**
   * doB Date
   * @return doBDate
  **/
  @ApiModelProperty(value = "doB Date")
  public OffsetDateTime getDoBDate() {
    return doBDate;
  }

  public void setDoBDate(OffsetDateTime doBDate) {
    this.doBDate = doBDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CharacterSheet characterSheet = (CharacterSheet) o;
    return Objects.equals(this.cid, characterSheet.cid) &&
        Objects.equals(this.eveKitVersion, characterSheet.eveKitVersion) &&
        Objects.equals(this.lifeStart, characterSheet.lifeStart) &&
        Objects.equals(this.lifeEnd, characterSheet.lifeEnd) &&
        Objects.equals(this.characterID, characterSheet.characterID) &&
        Objects.equals(this.name, characterSheet.name) &&
        Objects.equals(this.corporationID, characterSheet.corporationID) &&
        Objects.equals(this.raceID, characterSheet.raceID) &&
        Objects.equals(this.doB, characterSheet.doB) &&
        Objects.equals(this.bloodlineID, characterSheet.bloodlineID) &&
        Objects.equals(this.ancestryID, characterSheet.ancestryID) &&
        Objects.equals(this.gender, characterSheet.gender) &&
        Objects.equals(this.allianceID, characterSheet.allianceID) &&
        Objects.equals(this.factionID, characterSheet.factionID) &&
        Objects.equals(this.description, characterSheet.description) &&
        Objects.equals(this.securityStatus, characterSheet.securityStatus) &&
        Objects.equals(this.lifeStartDate, characterSheet.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, characterSheet.lifeEndDate) &&
        Objects.equals(this.doBDate, characterSheet.doBDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, characterID, name, corporationID, raceID, doB, bloodlineID, ancestryID, gender, allianceID, factionID, description, securityStatus, lifeStartDate, lifeEndDate, doBDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CharacterSheet {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    characterID: ").append(toIndentedString(characterID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    corporationID: ").append(toIndentedString(corporationID)).append("\n");
    sb.append("    raceID: ").append(toIndentedString(raceID)).append("\n");
    sb.append("    doB: ").append(toIndentedString(doB)).append("\n");
    sb.append("    bloodlineID: ").append(toIndentedString(bloodlineID)).append("\n");
    sb.append("    ancestryID: ").append(toIndentedString(ancestryID)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    allianceID: ").append(toIndentedString(allianceID)).append("\n");
    sb.append("    factionID: ").append(toIndentedString(factionID)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    securityStatus: ").append(toIndentedString(securityStatus)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("    doBDate: ").append(toIndentedString(doBDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

