/*
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import enterprises.orbital.evekit.client.model.MailMessageRecipient;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class CharacterMailMessage implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("messageID")
  private Long messageID = null;

  @JsonProperty("senderID")
  private Integer senderID = null;

  @JsonProperty("sentDate")
  private Long sentDate = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("msgRead")
  private Boolean msgRead = false;

  @JsonProperty("labels")
  private List<Integer> labels = new ArrayList<Integer>();

  @JsonProperty("recipients")
  private List<MailMessageRecipient> recipients = new ArrayList<MailMessageRecipient>();

  @JsonProperty("body")
  private String body = null;

  @JsonProperty("lifeStartDate")
  private OffsetDateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private OffsetDateTime lifeEndDate = null;

  @JsonProperty("sentDateDate")
  private OffsetDateTime sentDateDate = null;

  public CharacterMailMessage cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public CharacterMailMessage eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public CharacterMailMessage lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public CharacterMailMessage lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public CharacterMailMessage messageID(Long messageID) {
    this.messageID = messageID;
    return this;
  }

   /**
   * Get messageID
   * @return messageID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMessageID() {
    return messageID;
  }

  public void setMessageID(Long messageID) {
    this.messageID = messageID;
  }

  public CharacterMailMessage senderID(Integer senderID) {
    this.senderID = senderID;
    return this;
  }

   /**
   * Get senderID
   * @return senderID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSenderID() {
    return senderID;
  }

  public void setSenderID(Integer senderID) {
    this.senderID = senderID;
  }

  public CharacterMailMessage sentDate(Long sentDate) {
    this.sentDate = sentDate;
    return this;
  }

   /**
   * Get sentDate
   * @return sentDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSentDate() {
    return sentDate;
  }

  public void setSentDate(Long sentDate) {
    this.sentDate = sentDate;
  }

  public CharacterMailMessage title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public CharacterMailMessage msgRead(Boolean msgRead) {
    this.msgRead = msgRead;
    return this;
  }

   /**
   * Get msgRead
   * @return msgRead
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMsgRead() {
    return msgRead;
  }

  public void setMsgRead(Boolean msgRead) {
    this.msgRead = msgRead;
  }

  public CharacterMailMessage labels(List<Integer> labels) {
    this.labels = labels;
    return this;
  }

  public CharacterMailMessage addLabelsItem(Integer labelsItem) {
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Integer> getLabels() {
    return labels;
  }

  public void setLabels(List<Integer> labels) {
    this.labels = labels;
  }

  public CharacterMailMessage recipients(List<MailMessageRecipient> recipients) {
    this.recipients = recipients;
    return this;
  }

  public CharacterMailMessage addRecipientsItem(MailMessageRecipient recipientsItem) {
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Get recipients
   * @return recipients
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<MailMessageRecipient> getRecipients() {
    return recipients;
  }

  public void setRecipients(List<MailMessageRecipient> recipients) {
    this.recipients = recipients;
  }

  public CharacterMailMessage body(String body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public CharacterMailMessage lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public CharacterMailMessage lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }

  public CharacterMailMessage sentDateDate(OffsetDateTime sentDateDate) {
    this.sentDateDate = sentDateDate;
    return this;
  }

   /**
   * sentDate Date
   * @return sentDateDate
  **/
  @ApiModelProperty(example = "null", value = "sentDate Date")
  public OffsetDateTime getSentDateDate() {
    return sentDateDate;
  }

  public void setSentDateDate(OffsetDateTime sentDateDate) {
    this.sentDateDate = sentDateDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CharacterMailMessage characterMailMessage = (CharacterMailMessage) o;
    return Objects.equals(this.cid, characterMailMessage.cid) &&
        Objects.equals(this.eveKitVersion, characterMailMessage.eveKitVersion) &&
        Objects.equals(this.lifeStart, characterMailMessage.lifeStart) &&
        Objects.equals(this.lifeEnd, characterMailMessage.lifeEnd) &&
        Objects.equals(this.messageID, characterMailMessage.messageID) &&
        Objects.equals(this.senderID, characterMailMessage.senderID) &&
        Objects.equals(this.sentDate, characterMailMessage.sentDate) &&
        Objects.equals(this.title, characterMailMessage.title) &&
        Objects.equals(this.msgRead, characterMailMessage.msgRead) &&
        Objects.equals(this.labels, characterMailMessage.labels) &&
        Objects.equals(this.recipients, characterMailMessage.recipients) &&
        Objects.equals(this.body, characterMailMessage.body) &&
        Objects.equals(this.lifeStartDate, characterMailMessage.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, characterMailMessage.lifeEndDate) &&
        Objects.equals(this.sentDateDate, characterMailMessage.sentDateDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, messageID, senderID, sentDate, title, msgRead, labels, recipients, body, lifeStartDate, lifeEndDate, sentDateDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CharacterMailMessage {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    senderID: ").append(toIndentedString(senderID)).append("\n");
    sb.append("    sentDate: ").append(toIndentedString(sentDate)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    msgRead: ").append(toIndentedString(msgRead)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("    sentDateDate: ").append(toIndentedString(sentDateDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

