/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class CharacterSheetSkillPoints implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private Long cid;

  public static final String SERIALIZED_NAME_EVE_KIT_VERSION = "eveKitVersion";
  @SerializedName(SERIALIZED_NAME_EVE_KIT_VERSION)
  private Integer eveKitVersion;

  public static final String SERIALIZED_NAME_LIFE_START = "lifeStart";
  @SerializedName(SERIALIZED_NAME_LIFE_START)
  private Long lifeStart;

  public static final String SERIALIZED_NAME_LIFE_END = "lifeEnd";
  @SerializedName(SERIALIZED_NAME_LIFE_END)
  private Long lifeEnd;

  public static final String SERIALIZED_NAME_TOTAL_SKILL_POINTS = "totalSkillPoints";
  @SerializedName(SERIALIZED_NAME_TOTAL_SKILL_POINTS)
  private Long totalSkillPoints;

  public static final String SERIALIZED_NAME_UNALLOCATED_SKILL_POINTS = "unallocatedSkillPoints";
  @SerializedName(SERIALIZED_NAME_UNALLOCATED_SKILL_POINTS)
  private Integer unallocatedSkillPoints;

  public static final String SERIALIZED_NAME_LIFE_START_DATE = "lifeStartDate";
  @SerializedName(SERIALIZED_NAME_LIFE_START_DATE)
  private OffsetDateTime lifeStartDate;

  public static final String SERIALIZED_NAME_LIFE_END_DATE = "lifeEndDate";
  @SerializedName(SERIALIZED_NAME_LIFE_END_DATE)
  private OffsetDateTime lifeEndDate;

  public CharacterSheetSkillPoints cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public CharacterSheetSkillPoints eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public CharacterSheetSkillPoints lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public CharacterSheetSkillPoints lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public CharacterSheetSkillPoints totalSkillPoints(Long totalSkillPoints) {
    this.totalSkillPoints = totalSkillPoints;
    return this;
  }

   /**
   * Get totalSkillPoints
   * @return totalSkillPoints
  **/
  @ApiModelProperty(value = "")
  public Long getTotalSkillPoints() {
    return totalSkillPoints;
  }

  public void setTotalSkillPoints(Long totalSkillPoints) {
    this.totalSkillPoints = totalSkillPoints;
  }

  public CharacterSheetSkillPoints unallocatedSkillPoints(Integer unallocatedSkillPoints) {
    this.unallocatedSkillPoints = unallocatedSkillPoints;
    return this;
  }

   /**
   * Get unallocatedSkillPoints
   * @return unallocatedSkillPoints
  **/
  @ApiModelProperty(value = "")
  public Integer getUnallocatedSkillPoints() {
    return unallocatedSkillPoints;
  }

  public void setUnallocatedSkillPoints(Integer unallocatedSkillPoints) {
    this.unallocatedSkillPoints = unallocatedSkillPoints;
  }

  public CharacterSheetSkillPoints lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public CharacterSheetSkillPoints lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CharacterSheetSkillPoints characterSheetSkillPoints = (CharacterSheetSkillPoints) o;
    return Objects.equals(this.cid, characterSheetSkillPoints.cid) &&
        Objects.equals(this.eveKitVersion, characterSheetSkillPoints.eveKitVersion) &&
        Objects.equals(this.lifeStart, characterSheetSkillPoints.lifeStart) &&
        Objects.equals(this.lifeEnd, characterSheetSkillPoints.lifeEnd) &&
        Objects.equals(this.totalSkillPoints, characterSheetSkillPoints.totalSkillPoints) &&
        Objects.equals(this.unallocatedSkillPoints, characterSheetSkillPoints.unallocatedSkillPoints) &&
        Objects.equals(this.lifeStartDate, characterSheetSkillPoints.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, characterSheetSkillPoints.lifeEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, totalSkillPoints, unallocatedSkillPoints, lifeStartDate, lifeEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CharacterSheetSkillPoints {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    totalSkillPoints: ").append(toIndentedString(totalSkillPoints)).append("\n");
    sb.append("    unallocatedSkillPoints: ").append(toIndentedString(unallocatedSkillPoints)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

