/*
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class CharacterSheet implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("characterID")
  private Long characterID = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("corporationID")
  private Integer corporationID = null;

  @JsonProperty("raceID")
  private Integer raceID = null;

  @JsonProperty("doB")
  private Long doB = null;

  @JsonProperty("bloodlineID")
  private Integer bloodlineID = null;

  @JsonProperty("ancestryID")
  private Integer ancestryID = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("allianceID")
  private Integer allianceID = null;

  @JsonProperty("factionID")
  private Integer factionID = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("securityStatus")
  private Float securityStatus = null;

  @JsonProperty("lifeStartDate")
  private OffsetDateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private OffsetDateTime lifeEndDate = null;

  @JsonProperty("doBDate")
  private OffsetDateTime doBDate = null;

  public CharacterSheet cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public CharacterSheet eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public CharacterSheet lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public CharacterSheet lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public CharacterSheet characterID(Long characterID) {
    this.characterID = characterID;
    return this;
  }

   /**
   * Get characterID
   * @return characterID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCharacterID() {
    return characterID;
  }

  public void setCharacterID(Long characterID) {
    this.characterID = characterID;
  }

  public CharacterSheet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CharacterSheet corporationID(Integer corporationID) {
    this.corporationID = corporationID;
    return this;
  }

   /**
   * Get corporationID
   * @return corporationID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCorporationID() {
    return corporationID;
  }

  public void setCorporationID(Integer corporationID) {
    this.corporationID = corporationID;
  }

  public CharacterSheet raceID(Integer raceID) {
    this.raceID = raceID;
    return this;
  }

   /**
   * Get raceID
   * @return raceID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRaceID() {
    return raceID;
  }

  public void setRaceID(Integer raceID) {
    this.raceID = raceID;
  }

  public CharacterSheet doB(Long doB) {
    this.doB = doB;
    return this;
  }

   /**
   * Get doB
   * @return doB
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDoB() {
    return doB;
  }

  public void setDoB(Long doB) {
    this.doB = doB;
  }

  public CharacterSheet bloodlineID(Integer bloodlineID) {
    this.bloodlineID = bloodlineID;
    return this;
  }

   /**
   * Get bloodlineID
   * @return bloodlineID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBloodlineID() {
    return bloodlineID;
  }

  public void setBloodlineID(Integer bloodlineID) {
    this.bloodlineID = bloodlineID;
  }

  public CharacterSheet ancestryID(Integer ancestryID) {
    this.ancestryID = ancestryID;
    return this;
  }

   /**
   * Get ancestryID
   * @return ancestryID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAncestryID() {
    return ancestryID;
  }

  public void setAncestryID(Integer ancestryID) {
    this.ancestryID = ancestryID;
  }

  public CharacterSheet gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public CharacterSheet allianceID(Integer allianceID) {
    this.allianceID = allianceID;
    return this;
  }

   /**
   * Get allianceID
   * @return allianceID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAllianceID() {
    return allianceID;
  }

  public void setAllianceID(Integer allianceID) {
    this.allianceID = allianceID;
  }

  public CharacterSheet factionID(Integer factionID) {
    this.factionID = factionID;
    return this;
  }

   /**
   * Get factionID
   * @return factionID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFactionID() {
    return factionID;
  }

  public void setFactionID(Integer factionID) {
    this.factionID = factionID;
  }

  public CharacterSheet description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CharacterSheet securityStatus(Float securityStatus) {
    this.securityStatus = securityStatus;
    return this;
  }

   /**
   * Get securityStatus
   * @return securityStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getSecurityStatus() {
    return securityStatus;
  }

  public void setSecurityStatus(Float securityStatus) {
    this.securityStatus = securityStatus;
  }

  public CharacterSheet lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public CharacterSheet lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }

  public CharacterSheet doBDate(OffsetDateTime doBDate) {
    this.doBDate = doBDate;
    return this;
  }

   /**
   * doB Date
   * @return doBDate
  **/
  @ApiModelProperty(example = "null", value = "doB Date")
  public OffsetDateTime getDoBDate() {
    return doBDate;
  }

  public void setDoBDate(OffsetDateTime doBDate) {
    this.doBDate = doBDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CharacterSheet characterSheet = (CharacterSheet) o;
    return Objects.equals(this.cid, characterSheet.cid) &&
        Objects.equals(this.eveKitVersion, characterSheet.eveKitVersion) &&
        Objects.equals(this.lifeStart, characterSheet.lifeStart) &&
        Objects.equals(this.lifeEnd, characterSheet.lifeEnd) &&
        Objects.equals(this.characterID, characterSheet.characterID) &&
        Objects.equals(this.name, characterSheet.name) &&
        Objects.equals(this.corporationID, characterSheet.corporationID) &&
        Objects.equals(this.raceID, characterSheet.raceID) &&
        Objects.equals(this.doB, characterSheet.doB) &&
        Objects.equals(this.bloodlineID, characterSheet.bloodlineID) &&
        Objects.equals(this.ancestryID, characterSheet.ancestryID) &&
        Objects.equals(this.gender, characterSheet.gender) &&
        Objects.equals(this.allianceID, characterSheet.allianceID) &&
        Objects.equals(this.factionID, characterSheet.factionID) &&
        Objects.equals(this.description, characterSheet.description) &&
        Objects.equals(this.securityStatus, characterSheet.securityStatus) &&
        Objects.equals(this.lifeStartDate, characterSheet.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, characterSheet.lifeEndDate) &&
        Objects.equals(this.doBDate, characterSheet.doBDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, characterID, name, corporationID, raceID, doB, bloodlineID, ancestryID, gender, allianceID, factionID, description, securityStatus, lifeStartDate, lifeEndDate, doBDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CharacterSheet {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    characterID: ").append(toIndentedString(characterID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    corporationID: ").append(toIndentedString(corporationID)).append("\n");
    sb.append("    raceID: ").append(toIndentedString(raceID)).append("\n");
    sb.append("    doB: ").append(toIndentedString(doB)).append("\n");
    sb.append("    bloodlineID: ").append(toIndentedString(bloodlineID)).append("\n");
    sb.append("    ancestryID: ").append(toIndentedString(ancestryID)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    allianceID: ").append(toIndentedString(allianceID)).append("\n");
    sb.append("    factionID: ").append(toIndentedString(factionID)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    securityStatus: ").append(toIndentedString(securityStatus)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("    doBDate: ").append(toIndentedString(doBDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

