/**
 * EveKit Model API Server
 * 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-01T15:58:15.972+02:00")
public class CorporationTitle   {
  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("titleID")
  private Long titleID = null;

  @JsonProperty("titleName")
  private String titleName = null;

  @JsonProperty("grantableRoles")
  private List<Long> grantableRoles = new ArrayList<Long>();

  @JsonProperty("grantableRolesAtBase")
  private List<Long> grantableRolesAtBase = new ArrayList<Long>();

  @JsonProperty("grantableRolesAtHQ")
  private List<Long> grantableRolesAtHQ = new ArrayList<Long>();

  @JsonProperty("grantableRolesAtOther")
  private List<Long> grantableRolesAtOther = new ArrayList<Long>();

  @JsonProperty("roles")
  private List<Long> roles = new ArrayList<Long>();

  @JsonProperty("rolesAtBase")
  private List<Long> rolesAtBase = new ArrayList<Long>();

  @JsonProperty("rolesAtHQ")
  private List<Long> rolesAtHQ = new ArrayList<Long>();

  @JsonProperty("rolesAtOther")
  private List<Long> rolesAtOther = new ArrayList<Long>();

  @JsonProperty("lifeStartDate")
  private DateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private DateTime lifeEndDate = null;

  public CorporationTitle cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public CorporationTitle eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public CorporationTitle lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public CorporationTitle lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public CorporationTitle titleID(Long titleID) {
    this.titleID = titleID;
    return this;
  }

   /**
   * Get titleID
   * @return titleID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTitleID() {
    return titleID;
  }

  public void setTitleID(Long titleID) {
    this.titleID = titleID;
  }

  public CorporationTitle titleName(String titleName) {
    this.titleName = titleName;
    return this;
  }

   /**
   * Get titleName
   * @return titleName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitleName() {
    return titleName;
  }

  public void setTitleName(String titleName) {
    this.titleName = titleName;
  }

  public CorporationTitle grantableRoles(List<Long> grantableRoles) {
    this.grantableRoles = grantableRoles;
    return this;
  }

   /**
   * Get grantableRoles
   * @return grantableRoles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRoles() {
    return grantableRoles;
  }

  public void setGrantableRoles(List<Long> grantableRoles) {
    this.grantableRoles = grantableRoles;
  }

  public CorporationTitle grantableRolesAtBase(List<Long> grantableRolesAtBase) {
    this.grantableRolesAtBase = grantableRolesAtBase;
    return this;
  }

   /**
   * Get grantableRolesAtBase
   * @return grantableRolesAtBase
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRolesAtBase() {
    return grantableRolesAtBase;
  }

  public void setGrantableRolesAtBase(List<Long> grantableRolesAtBase) {
    this.grantableRolesAtBase = grantableRolesAtBase;
  }

  public CorporationTitle grantableRolesAtHQ(List<Long> grantableRolesAtHQ) {
    this.grantableRolesAtHQ = grantableRolesAtHQ;
    return this;
  }

   /**
   * Get grantableRolesAtHQ
   * @return grantableRolesAtHQ
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRolesAtHQ() {
    return grantableRolesAtHQ;
  }

  public void setGrantableRolesAtHQ(List<Long> grantableRolesAtHQ) {
    this.grantableRolesAtHQ = grantableRolesAtHQ;
  }

  public CorporationTitle grantableRolesAtOther(List<Long> grantableRolesAtOther) {
    this.grantableRolesAtOther = grantableRolesAtOther;
    return this;
  }

   /**
   * Get grantableRolesAtOther
   * @return grantableRolesAtOther
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRolesAtOther() {
    return grantableRolesAtOther;
  }

  public void setGrantableRolesAtOther(List<Long> grantableRolesAtOther) {
    this.grantableRolesAtOther = grantableRolesAtOther;
  }

  public CorporationTitle roles(List<Long> roles) {
    this.roles = roles;
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRoles() {
    return roles;
  }

  public void setRoles(List<Long> roles) {
    this.roles = roles;
  }

  public CorporationTitle rolesAtBase(List<Long> rolesAtBase) {
    this.rolesAtBase = rolesAtBase;
    return this;
  }

   /**
   * Get rolesAtBase
   * @return rolesAtBase
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRolesAtBase() {
    return rolesAtBase;
  }

  public void setRolesAtBase(List<Long> rolesAtBase) {
    this.rolesAtBase = rolesAtBase;
  }

  public CorporationTitle rolesAtHQ(List<Long> rolesAtHQ) {
    this.rolesAtHQ = rolesAtHQ;
    return this;
  }

   /**
   * Get rolesAtHQ
   * @return rolesAtHQ
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRolesAtHQ() {
    return rolesAtHQ;
  }

  public void setRolesAtHQ(List<Long> rolesAtHQ) {
    this.rolesAtHQ = rolesAtHQ;
  }

  public CorporationTitle rolesAtOther(List<Long> rolesAtOther) {
    this.rolesAtOther = rolesAtOther;
    return this;
  }

   /**
   * Get rolesAtOther
   * @return rolesAtOther
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRolesAtOther() {
    return rolesAtOther;
  }

  public void setRolesAtOther(List<Long> rolesAtOther) {
    this.rolesAtOther = rolesAtOther;
  }

  public CorporationTitle lifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public DateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public CorporationTitle lifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public DateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorporationTitle corporationTitle = (CorporationTitle) o;
    return Objects.equals(this.cid, corporationTitle.cid) &&
        Objects.equals(this.eveKitVersion, corporationTitle.eveKitVersion) &&
        Objects.equals(this.lifeStart, corporationTitle.lifeStart) &&
        Objects.equals(this.lifeEnd, corporationTitle.lifeEnd) &&
        Objects.equals(this.titleID, corporationTitle.titleID) &&
        Objects.equals(this.titleName, corporationTitle.titleName) &&
        Objects.equals(this.grantableRoles, corporationTitle.grantableRoles) &&
        Objects.equals(this.grantableRolesAtBase, corporationTitle.grantableRolesAtBase) &&
        Objects.equals(this.grantableRolesAtHQ, corporationTitle.grantableRolesAtHQ) &&
        Objects.equals(this.grantableRolesAtOther, corporationTitle.grantableRolesAtOther) &&
        Objects.equals(this.roles, corporationTitle.roles) &&
        Objects.equals(this.rolesAtBase, corporationTitle.rolesAtBase) &&
        Objects.equals(this.rolesAtHQ, corporationTitle.rolesAtHQ) &&
        Objects.equals(this.rolesAtOther, corporationTitle.rolesAtOther) &&
        Objects.equals(this.lifeStartDate, corporationTitle.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, corporationTitle.lifeEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, titleID, titleName, grantableRoles, grantableRolesAtBase, grantableRolesAtHQ, grantableRolesAtOther, roles, rolesAtBase, rolesAtHQ, rolesAtOther, lifeStartDate, lifeEndDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorporationTitle {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    titleID: ").append(toIndentedString(titleID)).append("\n");
    sb.append("    titleName: ").append(toIndentedString(titleName)).append("\n");
    sb.append("    grantableRoles: ").append(toIndentedString(grantableRoles)).append("\n");
    sb.append("    grantableRolesAtBase: ").append(toIndentedString(grantableRolesAtBase)).append("\n");
    sb.append("    grantableRolesAtHQ: ").append(toIndentedString(grantableRolesAtHQ)).append("\n");
    sb.append("    grantableRolesAtOther: ").append(toIndentedString(grantableRolesAtOther)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    rolesAtBase: ").append(toIndentedString(rolesAtBase)).append("\n");
    sb.append("    rolesAtHQ: ").append(toIndentedString(rolesAtHQ)).append("\n");
    sb.append("    rolesAtOther: ").append(toIndentedString(rolesAtOther)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

