/*
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class CustomsOffice implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("officeID")
  private Long officeID = null;

  @JsonProperty("solarSystemID")
  private Integer solarSystemID = null;

  @JsonProperty("reinforceExitStart")
  private Integer reinforceExitStart = null;

  @JsonProperty("reinforceExitEnd")
  private Integer reinforceExitEnd = null;

  @JsonProperty("allowAlliance")
  private Boolean allowAlliance = false;

  @JsonProperty("allowStandings")
  private Boolean allowStandings = false;

  @JsonProperty("standingLevel")
  private String standingLevel = null;

  @JsonProperty("taxRateAlliance")
  private Float taxRateAlliance = null;

  @JsonProperty("taxRateCorp")
  private Float taxRateCorp = null;

  @JsonProperty("taxRateStandingExcellent")
  private Float taxRateStandingExcellent = null;

  @JsonProperty("taxRateStandingGood")
  private Float taxRateStandingGood = null;

  @JsonProperty("taxRateStandingNeutral")
  private Float taxRateStandingNeutral = null;

  @JsonProperty("taxRateStandingBad")
  private Float taxRateStandingBad = null;

  @JsonProperty("taxRateStandingTerrible")
  private Float taxRateStandingTerrible = null;

  @JsonProperty("lifeStartDate")
  private OffsetDateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private OffsetDateTime lifeEndDate = null;

  public CustomsOffice cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public CustomsOffice eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public CustomsOffice lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public CustomsOffice lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public CustomsOffice officeID(Long officeID) {
    this.officeID = officeID;
    return this;
  }

   /**
   * Get officeID
   * @return officeID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getOfficeID() {
    return officeID;
  }

  public void setOfficeID(Long officeID) {
    this.officeID = officeID;
  }

  public CustomsOffice solarSystemID(Integer solarSystemID) {
    this.solarSystemID = solarSystemID;
    return this;
  }

   /**
   * Get solarSystemID
   * @return solarSystemID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSolarSystemID() {
    return solarSystemID;
  }

  public void setSolarSystemID(Integer solarSystemID) {
    this.solarSystemID = solarSystemID;
  }

  public CustomsOffice reinforceExitStart(Integer reinforceExitStart) {
    this.reinforceExitStart = reinforceExitStart;
    return this;
  }

   /**
   * Get reinforceExitStart
   * @return reinforceExitStart
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getReinforceExitStart() {
    return reinforceExitStart;
  }

  public void setReinforceExitStart(Integer reinforceExitStart) {
    this.reinforceExitStart = reinforceExitStart;
  }

  public CustomsOffice reinforceExitEnd(Integer reinforceExitEnd) {
    this.reinforceExitEnd = reinforceExitEnd;
    return this;
  }

   /**
   * Get reinforceExitEnd
   * @return reinforceExitEnd
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getReinforceExitEnd() {
    return reinforceExitEnd;
  }

  public void setReinforceExitEnd(Integer reinforceExitEnd) {
    this.reinforceExitEnd = reinforceExitEnd;
  }

  public CustomsOffice allowAlliance(Boolean allowAlliance) {
    this.allowAlliance = allowAlliance;
    return this;
  }

   /**
   * Get allowAlliance
   * @return allowAlliance
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAllowAlliance() {
    return allowAlliance;
  }

  public void setAllowAlliance(Boolean allowAlliance) {
    this.allowAlliance = allowAlliance;
  }

  public CustomsOffice allowStandings(Boolean allowStandings) {
    this.allowStandings = allowStandings;
    return this;
  }

   /**
   * Get allowStandings
   * @return allowStandings
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAllowStandings() {
    return allowStandings;
  }

  public void setAllowStandings(Boolean allowStandings) {
    this.allowStandings = allowStandings;
  }

  public CustomsOffice standingLevel(String standingLevel) {
    this.standingLevel = standingLevel;
    return this;
  }

   /**
   * Get standingLevel
   * @return standingLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStandingLevel() {
    return standingLevel;
  }

  public void setStandingLevel(String standingLevel) {
    this.standingLevel = standingLevel;
  }

  public CustomsOffice taxRateAlliance(Float taxRateAlliance) {
    this.taxRateAlliance = taxRateAlliance;
    return this;
  }

   /**
   * Get taxRateAlliance
   * @return taxRateAlliance
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTaxRateAlliance() {
    return taxRateAlliance;
  }

  public void setTaxRateAlliance(Float taxRateAlliance) {
    this.taxRateAlliance = taxRateAlliance;
  }

  public CustomsOffice taxRateCorp(Float taxRateCorp) {
    this.taxRateCorp = taxRateCorp;
    return this;
  }

   /**
   * Get taxRateCorp
   * @return taxRateCorp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTaxRateCorp() {
    return taxRateCorp;
  }

  public void setTaxRateCorp(Float taxRateCorp) {
    this.taxRateCorp = taxRateCorp;
  }

  public CustomsOffice taxRateStandingExcellent(Float taxRateStandingExcellent) {
    this.taxRateStandingExcellent = taxRateStandingExcellent;
    return this;
  }

   /**
   * Get taxRateStandingExcellent
   * @return taxRateStandingExcellent
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTaxRateStandingExcellent() {
    return taxRateStandingExcellent;
  }

  public void setTaxRateStandingExcellent(Float taxRateStandingExcellent) {
    this.taxRateStandingExcellent = taxRateStandingExcellent;
  }

  public CustomsOffice taxRateStandingGood(Float taxRateStandingGood) {
    this.taxRateStandingGood = taxRateStandingGood;
    return this;
  }

   /**
   * Get taxRateStandingGood
   * @return taxRateStandingGood
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTaxRateStandingGood() {
    return taxRateStandingGood;
  }

  public void setTaxRateStandingGood(Float taxRateStandingGood) {
    this.taxRateStandingGood = taxRateStandingGood;
  }

  public CustomsOffice taxRateStandingNeutral(Float taxRateStandingNeutral) {
    this.taxRateStandingNeutral = taxRateStandingNeutral;
    return this;
  }

   /**
   * Get taxRateStandingNeutral
   * @return taxRateStandingNeutral
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTaxRateStandingNeutral() {
    return taxRateStandingNeutral;
  }

  public void setTaxRateStandingNeutral(Float taxRateStandingNeutral) {
    this.taxRateStandingNeutral = taxRateStandingNeutral;
  }

  public CustomsOffice taxRateStandingBad(Float taxRateStandingBad) {
    this.taxRateStandingBad = taxRateStandingBad;
    return this;
  }

   /**
   * Get taxRateStandingBad
   * @return taxRateStandingBad
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTaxRateStandingBad() {
    return taxRateStandingBad;
  }

  public void setTaxRateStandingBad(Float taxRateStandingBad) {
    this.taxRateStandingBad = taxRateStandingBad;
  }

  public CustomsOffice taxRateStandingTerrible(Float taxRateStandingTerrible) {
    this.taxRateStandingTerrible = taxRateStandingTerrible;
    return this;
  }

   /**
   * Get taxRateStandingTerrible
   * @return taxRateStandingTerrible
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTaxRateStandingTerrible() {
    return taxRateStandingTerrible;
  }

  public void setTaxRateStandingTerrible(Float taxRateStandingTerrible) {
    this.taxRateStandingTerrible = taxRateStandingTerrible;
  }

  public CustomsOffice lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public CustomsOffice lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomsOffice customsOffice = (CustomsOffice) o;
    return Objects.equals(this.cid, customsOffice.cid) &&
        Objects.equals(this.eveKitVersion, customsOffice.eveKitVersion) &&
        Objects.equals(this.lifeStart, customsOffice.lifeStart) &&
        Objects.equals(this.lifeEnd, customsOffice.lifeEnd) &&
        Objects.equals(this.officeID, customsOffice.officeID) &&
        Objects.equals(this.solarSystemID, customsOffice.solarSystemID) &&
        Objects.equals(this.reinforceExitStart, customsOffice.reinforceExitStart) &&
        Objects.equals(this.reinforceExitEnd, customsOffice.reinforceExitEnd) &&
        Objects.equals(this.allowAlliance, customsOffice.allowAlliance) &&
        Objects.equals(this.allowStandings, customsOffice.allowStandings) &&
        Objects.equals(this.standingLevel, customsOffice.standingLevel) &&
        Objects.equals(this.taxRateAlliance, customsOffice.taxRateAlliance) &&
        Objects.equals(this.taxRateCorp, customsOffice.taxRateCorp) &&
        Objects.equals(this.taxRateStandingExcellent, customsOffice.taxRateStandingExcellent) &&
        Objects.equals(this.taxRateStandingGood, customsOffice.taxRateStandingGood) &&
        Objects.equals(this.taxRateStandingNeutral, customsOffice.taxRateStandingNeutral) &&
        Objects.equals(this.taxRateStandingBad, customsOffice.taxRateStandingBad) &&
        Objects.equals(this.taxRateStandingTerrible, customsOffice.taxRateStandingTerrible) &&
        Objects.equals(this.lifeStartDate, customsOffice.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, customsOffice.lifeEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, officeID, solarSystemID, reinforceExitStart, reinforceExitEnd, allowAlliance, allowStandings, standingLevel, taxRateAlliance, taxRateCorp, taxRateStandingExcellent, taxRateStandingGood, taxRateStandingNeutral, taxRateStandingBad, taxRateStandingTerrible, lifeStartDate, lifeEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomsOffice {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    officeID: ").append(toIndentedString(officeID)).append("\n");
    sb.append("    solarSystemID: ").append(toIndentedString(solarSystemID)).append("\n");
    sb.append("    reinforceExitStart: ").append(toIndentedString(reinforceExitStart)).append("\n");
    sb.append("    reinforceExitEnd: ").append(toIndentedString(reinforceExitEnd)).append("\n");
    sb.append("    allowAlliance: ").append(toIndentedString(allowAlliance)).append("\n");
    sb.append("    allowStandings: ").append(toIndentedString(allowStandings)).append("\n");
    sb.append("    standingLevel: ").append(toIndentedString(standingLevel)).append("\n");
    sb.append("    taxRateAlliance: ").append(toIndentedString(taxRateAlliance)).append("\n");
    sb.append("    taxRateCorp: ").append(toIndentedString(taxRateCorp)).append("\n");
    sb.append("    taxRateStandingExcellent: ").append(toIndentedString(taxRateStandingExcellent)).append("\n");
    sb.append("    taxRateStandingGood: ").append(toIndentedString(taxRateStandingGood)).append("\n");
    sb.append("    taxRateStandingNeutral: ").append(toIndentedString(taxRateStandingNeutral)).append("\n");
    sb.append("    taxRateStandingBad: ").append(toIndentedString(taxRateStandingBad)).append("\n");
    sb.append("    taxRateStandingTerrible: ").append(toIndentedString(taxRateStandingTerrible)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

