/*
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class FleetInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("fleetID")
  private Long fleetID = null;

  @JsonProperty("motd")
  private String motd = null;

  @JsonProperty("freeMove")
  private Boolean freeMove = false;

  @JsonProperty("voiceEnabled")
  private Boolean voiceEnabled = false;

  @JsonProperty("registered")
  private Boolean registered = false;

  @JsonProperty("lifeStartDate")
  private OffsetDateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private OffsetDateTime lifeEndDate = null;

  public FleetInfo cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public FleetInfo eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public FleetInfo lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public FleetInfo lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public FleetInfo fleetID(Long fleetID) {
    this.fleetID = fleetID;
    return this;
  }

   /**
   * Get fleetID
   * @return fleetID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getFleetID() {
    return fleetID;
  }

  public void setFleetID(Long fleetID) {
    this.fleetID = fleetID;
  }

  public FleetInfo motd(String motd) {
    this.motd = motd;
    return this;
  }

   /**
   * Get motd
   * @return motd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMotd() {
    return motd;
  }

  public void setMotd(String motd) {
    this.motd = motd;
  }

  public FleetInfo freeMove(Boolean freeMove) {
    this.freeMove = freeMove;
    return this;
  }

   /**
   * Get freeMove
   * @return freeMove
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getFreeMove() {
    return freeMove;
  }

  public void setFreeMove(Boolean freeMove) {
    this.freeMove = freeMove;
  }

  public FleetInfo voiceEnabled(Boolean voiceEnabled) {
    this.voiceEnabled = voiceEnabled;
    return this;
  }

   /**
   * Get voiceEnabled
   * @return voiceEnabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getVoiceEnabled() {
    return voiceEnabled;
  }

  public void setVoiceEnabled(Boolean voiceEnabled) {
    this.voiceEnabled = voiceEnabled;
  }

  public FleetInfo registered(Boolean registered) {
    this.registered = registered;
    return this;
  }

   /**
   * Get registered
   * @return registered
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getRegistered() {
    return registered;
  }

  public void setRegistered(Boolean registered) {
    this.registered = registered;
  }

  public FleetInfo lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public FleetInfo lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FleetInfo fleetInfo = (FleetInfo) o;
    return Objects.equals(this.cid, fleetInfo.cid) &&
        Objects.equals(this.eveKitVersion, fleetInfo.eveKitVersion) &&
        Objects.equals(this.lifeStart, fleetInfo.lifeStart) &&
        Objects.equals(this.lifeEnd, fleetInfo.lifeEnd) &&
        Objects.equals(this.fleetID, fleetInfo.fleetID) &&
        Objects.equals(this.motd, fleetInfo.motd) &&
        Objects.equals(this.freeMove, fleetInfo.freeMove) &&
        Objects.equals(this.voiceEnabled, fleetInfo.voiceEnabled) &&
        Objects.equals(this.registered, fleetInfo.registered) &&
        Objects.equals(this.lifeStartDate, fleetInfo.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, fleetInfo.lifeEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, fleetID, motd, freeMove, voiceEnabled, registered, lifeStartDate, lifeEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FleetInfo {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    fleetID: ").append(toIndentedString(fleetID)).append("\n");
    sb.append("    motd: ").append(toIndentedString(motd)).append("\n");
    sb.append("    freeMove: ").append(toIndentedString(freeMove)).append("\n");
    sb.append("    voiceEnabled: ").append(toIndentedString(voiceEnabled)).append("\n");
    sb.append("    registered: ").append(toIndentedString(registered)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

