/**
 * EveKit Model API Server
 * 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.joda.time.DateTime;


/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-01T15:58:15.972+02:00")
public class IndustryJob   {
  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("jobID")
  private Long jobID = null;

  @JsonProperty("installerID")
  private Long installerID = null;

  @JsonProperty("installerName")
  private String installerName = null;

  @JsonProperty("facilityID")
  private Long facilityID = null;

  @JsonProperty("solarSystemID")
  private Integer solarSystemID = null;

  @JsonProperty("solarSystemName")
  private String solarSystemName = null;

  @JsonProperty("stationID")
  private Long stationID = null;

  @JsonProperty("activityID")
  private Integer activityID = null;

  @JsonProperty("blueprintID")
  private Long blueprintID = null;

  @JsonProperty("blueprintTypeID")
  private Integer blueprintTypeID = null;

  @JsonProperty("blueprintTypeName")
  private String blueprintTypeName = null;

  @JsonProperty("blueprintLocationID")
  private Long blueprintLocationID = null;

  @JsonProperty("outputLocationID")
  private Long outputLocationID = null;

  @JsonProperty("runs")
  private Integer runs = null;

  @JsonProperty("cost")
  private BigDecimal cost = null;

  @JsonProperty("teamID")
  private Long teamID = null;

  @JsonProperty("licensedRuns")
  private Integer licensedRuns = null;

  @JsonProperty("probability")
  private Double probability = null;

  @JsonProperty("productTypeID")
  private Integer productTypeID = null;

  @JsonProperty("productTypeName")
  private String productTypeName = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("timeInSeconds")
  private Integer timeInSeconds = null;

  @JsonProperty("startDate")
  private Long startDate = null;

  @JsonProperty("endDate")
  private Long endDate = null;

  @JsonProperty("pauseDate")
  private Long pauseDate = null;

  @JsonProperty("completedDate")
  private Long completedDate = null;

  @JsonProperty("completedCharacterID")
  private Long completedCharacterID = null;

  @JsonProperty("successfulRuns")
  private Integer successfulRuns = null;

  @JsonProperty("lifeStartDate")
  private DateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private DateTime lifeEndDate = null;

  @JsonProperty("startDateDate")
  private DateTime startDateDate = null;

  @JsonProperty("endDateDate")
  private DateTime endDateDate = null;

  @JsonProperty("pauseDateDate")
  private DateTime pauseDateDate = null;

  @JsonProperty("completedDateDate")
  private DateTime completedDateDate = null;

  public IndustryJob cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public IndustryJob eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public IndustryJob lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public IndustryJob lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public IndustryJob jobID(Long jobID) {
    this.jobID = jobID;
    return this;
  }

   /**
   * Get jobID
   * @return jobID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getJobID() {
    return jobID;
  }

  public void setJobID(Long jobID) {
    this.jobID = jobID;
  }

  public IndustryJob installerID(Long installerID) {
    this.installerID = installerID;
    return this;
  }

   /**
   * Get installerID
   * @return installerID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getInstallerID() {
    return installerID;
  }

  public void setInstallerID(Long installerID) {
    this.installerID = installerID;
  }

  public IndustryJob installerName(String installerName) {
    this.installerName = installerName;
    return this;
  }

   /**
   * Get installerName
   * @return installerName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInstallerName() {
    return installerName;
  }

  public void setInstallerName(String installerName) {
    this.installerName = installerName;
  }

  public IndustryJob facilityID(Long facilityID) {
    this.facilityID = facilityID;
    return this;
  }

   /**
   * Get facilityID
   * @return facilityID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getFacilityID() {
    return facilityID;
  }

  public void setFacilityID(Long facilityID) {
    this.facilityID = facilityID;
  }

  public IndustryJob solarSystemID(Integer solarSystemID) {
    this.solarSystemID = solarSystemID;
    return this;
  }

   /**
   * Get solarSystemID
   * @return solarSystemID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSolarSystemID() {
    return solarSystemID;
  }

  public void setSolarSystemID(Integer solarSystemID) {
    this.solarSystemID = solarSystemID;
  }

  public IndustryJob solarSystemName(String solarSystemName) {
    this.solarSystemName = solarSystemName;
    return this;
  }

   /**
   * Get solarSystemName
   * @return solarSystemName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSolarSystemName() {
    return solarSystemName;
  }

  public void setSolarSystemName(String solarSystemName) {
    this.solarSystemName = solarSystemName;
  }

  public IndustryJob stationID(Long stationID) {
    this.stationID = stationID;
    return this;
  }

   /**
   * Get stationID
   * @return stationID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStationID() {
    return stationID;
  }

  public void setStationID(Long stationID) {
    this.stationID = stationID;
  }

  public IndustryJob activityID(Integer activityID) {
    this.activityID = activityID;
    return this;
  }

   /**
   * Get activityID
   * @return activityID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getActivityID() {
    return activityID;
  }

  public void setActivityID(Integer activityID) {
    this.activityID = activityID;
  }

  public IndustryJob blueprintID(Long blueprintID) {
    this.blueprintID = blueprintID;
    return this;
  }

   /**
   * Get blueprintID
   * @return blueprintID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBlueprintID() {
    return blueprintID;
  }

  public void setBlueprintID(Long blueprintID) {
    this.blueprintID = blueprintID;
  }

  public IndustryJob blueprintTypeID(Integer blueprintTypeID) {
    this.blueprintTypeID = blueprintTypeID;
    return this;
  }

   /**
   * Get blueprintTypeID
   * @return blueprintTypeID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBlueprintTypeID() {
    return blueprintTypeID;
  }

  public void setBlueprintTypeID(Integer blueprintTypeID) {
    this.blueprintTypeID = blueprintTypeID;
  }

  public IndustryJob blueprintTypeName(String blueprintTypeName) {
    this.blueprintTypeName = blueprintTypeName;
    return this;
  }

   /**
   * Get blueprintTypeName
   * @return blueprintTypeName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBlueprintTypeName() {
    return blueprintTypeName;
  }

  public void setBlueprintTypeName(String blueprintTypeName) {
    this.blueprintTypeName = blueprintTypeName;
  }

  public IndustryJob blueprintLocationID(Long blueprintLocationID) {
    this.blueprintLocationID = blueprintLocationID;
    return this;
  }

   /**
   * Get blueprintLocationID
   * @return blueprintLocationID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBlueprintLocationID() {
    return blueprintLocationID;
  }

  public void setBlueprintLocationID(Long blueprintLocationID) {
    this.blueprintLocationID = blueprintLocationID;
  }

  public IndustryJob outputLocationID(Long outputLocationID) {
    this.outputLocationID = outputLocationID;
    return this;
  }

   /**
   * Get outputLocationID
   * @return outputLocationID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getOutputLocationID() {
    return outputLocationID;
  }

  public void setOutputLocationID(Long outputLocationID) {
    this.outputLocationID = outputLocationID;
  }

  public IndustryJob runs(Integer runs) {
    this.runs = runs;
    return this;
  }

   /**
   * Get runs
   * @return runs
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRuns() {
    return runs;
  }

  public void setRuns(Integer runs) {
    this.runs = runs;
  }

  public IndustryJob cost(BigDecimal cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getCost() {
    return cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }

  public IndustryJob teamID(Long teamID) {
    this.teamID = teamID;
    return this;
  }

   /**
   * Get teamID
   * @return teamID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTeamID() {
    return teamID;
  }

  public void setTeamID(Long teamID) {
    this.teamID = teamID;
  }

  public IndustryJob licensedRuns(Integer licensedRuns) {
    this.licensedRuns = licensedRuns;
    return this;
  }

   /**
   * Get licensedRuns
   * @return licensedRuns
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLicensedRuns() {
    return licensedRuns;
  }

  public void setLicensedRuns(Integer licensedRuns) {
    this.licensedRuns = licensedRuns;
  }

  public IndustryJob probability(Double probability) {
    this.probability = probability;
    return this;
  }

   /**
   * Get probability
   * @return probability
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getProbability() {
    return probability;
  }

  public void setProbability(Double probability) {
    this.probability = probability;
  }

  public IndustryJob productTypeID(Integer productTypeID) {
    this.productTypeID = productTypeID;
    return this;
  }

   /**
   * Get productTypeID
   * @return productTypeID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getProductTypeID() {
    return productTypeID;
  }

  public void setProductTypeID(Integer productTypeID) {
    this.productTypeID = productTypeID;
  }

  public IndustryJob productTypeName(String productTypeName) {
    this.productTypeName = productTypeName;
    return this;
  }

   /**
   * Get productTypeName
   * @return productTypeName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProductTypeName() {
    return productTypeName;
  }

  public void setProductTypeName(String productTypeName) {
    this.productTypeName = productTypeName;
  }

  public IndustryJob status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public IndustryJob timeInSeconds(Integer timeInSeconds) {
    this.timeInSeconds = timeInSeconds;
    return this;
  }

   /**
   * Get timeInSeconds
   * @return timeInSeconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTimeInSeconds() {
    return timeInSeconds;
  }

  public void setTimeInSeconds(Integer timeInSeconds) {
    this.timeInSeconds = timeInSeconds;
  }

  public IndustryJob startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public IndustryJob endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public IndustryJob pauseDate(Long pauseDate) {
    this.pauseDate = pauseDate;
    return this;
  }

   /**
   * Get pauseDate
   * @return pauseDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPauseDate() {
    return pauseDate;
  }

  public void setPauseDate(Long pauseDate) {
    this.pauseDate = pauseDate;
  }

  public IndustryJob completedDate(Long completedDate) {
    this.completedDate = completedDate;
    return this;
  }

   /**
   * Get completedDate
   * @return completedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCompletedDate() {
    return completedDate;
  }

  public void setCompletedDate(Long completedDate) {
    this.completedDate = completedDate;
  }

  public IndustryJob completedCharacterID(Long completedCharacterID) {
    this.completedCharacterID = completedCharacterID;
    return this;
  }

   /**
   * Get completedCharacterID
   * @return completedCharacterID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCompletedCharacterID() {
    return completedCharacterID;
  }

  public void setCompletedCharacterID(Long completedCharacterID) {
    this.completedCharacterID = completedCharacterID;
  }

  public IndustryJob successfulRuns(Integer successfulRuns) {
    this.successfulRuns = successfulRuns;
    return this;
  }

   /**
   * Get successfulRuns
   * @return successfulRuns
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSuccessfulRuns() {
    return successfulRuns;
  }

  public void setSuccessfulRuns(Integer successfulRuns) {
    this.successfulRuns = successfulRuns;
  }

  public IndustryJob lifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public DateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public IndustryJob lifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public DateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }

  public IndustryJob startDateDate(DateTime startDateDate) {
    this.startDateDate = startDateDate;
    return this;
  }

   /**
   * startDate Date
   * @return startDateDate
  **/
  @ApiModelProperty(example = "null", value = "startDate Date")
  public DateTime getStartDateDate() {
    return startDateDate;
  }

  public void setStartDateDate(DateTime startDateDate) {
    this.startDateDate = startDateDate;
  }

  public IndustryJob endDateDate(DateTime endDateDate) {
    this.endDateDate = endDateDate;
    return this;
  }

   /**
   * endDate Date
   * @return endDateDate
  **/
  @ApiModelProperty(example = "null", value = "endDate Date")
  public DateTime getEndDateDate() {
    return endDateDate;
  }

  public void setEndDateDate(DateTime endDateDate) {
    this.endDateDate = endDateDate;
  }

  public IndustryJob pauseDateDate(DateTime pauseDateDate) {
    this.pauseDateDate = pauseDateDate;
    return this;
  }

   /**
   * pauseDate Date
   * @return pauseDateDate
  **/
  @ApiModelProperty(example = "null", value = "pauseDate Date")
  public DateTime getPauseDateDate() {
    return pauseDateDate;
  }

  public void setPauseDateDate(DateTime pauseDateDate) {
    this.pauseDateDate = pauseDateDate;
  }

  public IndustryJob completedDateDate(DateTime completedDateDate) {
    this.completedDateDate = completedDateDate;
    return this;
  }

   /**
   * completedDate Date
   * @return completedDateDate
  **/
  @ApiModelProperty(example = "null", value = "completedDate Date")
  public DateTime getCompletedDateDate() {
    return completedDateDate;
  }

  public void setCompletedDateDate(DateTime completedDateDate) {
    this.completedDateDate = completedDateDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndustryJob industryJob = (IndustryJob) o;
    return Objects.equals(this.cid, industryJob.cid) &&
        Objects.equals(this.eveKitVersion, industryJob.eveKitVersion) &&
        Objects.equals(this.lifeStart, industryJob.lifeStart) &&
        Objects.equals(this.lifeEnd, industryJob.lifeEnd) &&
        Objects.equals(this.jobID, industryJob.jobID) &&
        Objects.equals(this.installerID, industryJob.installerID) &&
        Objects.equals(this.installerName, industryJob.installerName) &&
        Objects.equals(this.facilityID, industryJob.facilityID) &&
        Objects.equals(this.solarSystemID, industryJob.solarSystemID) &&
        Objects.equals(this.solarSystemName, industryJob.solarSystemName) &&
        Objects.equals(this.stationID, industryJob.stationID) &&
        Objects.equals(this.activityID, industryJob.activityID) &&
        Objects.equals(this.blueprintID, industryJob.blueprintID) &&
        Objects.equals(this.blueprintTypeID, industryJob.blueprintTypeID) &&
        Objects.equals(this.blueprintTypeName, industryJob.blueprintTypeName) &&
        Objects.equals(this.blueprintLocationID, industryJob.blueprintLocationID) &&
        Objects.equals(this.outputLocationID, industryJob.outputLocationID) &&
        Objects.equals(this.runs, industryJob.runs) &&
        Objects.equals(this.cost, industryJob.cost) &&
        Objects.equals(this.teamID, industryJob.teamID) &&
        Objects.equals(this.licensedRuns, industryJob.licensedRuns) &&
        Objects.equals(this.probability, industryJob.probability) &&
        Objects.equals(this.productTypeID, industryJob.productTypeID) &&
        Objects.equals(this.productTypeName, industryJob.productTypeName) &&
        Objects.equals(this.status, industryJob.status) &&
        Objects.equals(this.timeInSeconds, industryJob.timeInSeconds) &&
        Objects.equals(this.startDate, industryJob.startDate) &&
        Objects.equals(this.endDate, industryJob.endDate) &&
        Objects.equals(this.pauseDate, industryJob.pauseDate) &&
        Objects.equals(this.completedDate, industryJob.completedDate) &&
        Objects.equals(this.completedCharacterID, industryJob.completedCharacterID) &&
        Objects.equals(this.successfulRuns, industryJob.successfulRuns) &&
        Objects.equals(this.lifeStartDate, industryJob.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, industryJob.lifeEndDate) &&
        Objects.equals(this.startDateDate, industryJob.startDateDate) &&
        Objects.equals(this.endDateDate, industryJob.endDateDate) &&
        Objects.equals(this.pauseDateDate, industryJob.pauseDateDate) &&
        Objects.equals(this.completedDateDate, industryJob.completedDateDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, jobID, installerID, installerName, facilityID, solarSystemID, solarSystemName, stationID, activityID, blueprintID, blueprintTypeID, blueprintTypeName, blueprintLocationID, outputLocationID, runs, cost, teamID, licensedRuns, probability, productTypeID, productTypeName, status, timeInSeconds, startDate, endDate, pauseDate, completedDate, completedCharacterID, successfulRuns, lifeStartDate, lifeEndDate, startDateDate, endDateDate, pauseDateDate, completedDateDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndustryJob {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    jobID: ").append(toIndentedString(jobID)).append("\n");
    sb.append("    installerID: ").append(toIndentedString(installerID)).append("\n");
    sb.append("    installerName: ").append(toIndentedString(installerName)).append("\n");
    sb.append("    facilityID: ").append(toIndentedString(facilityID)).append("\n");
    sb.append("    solarSystemID: ").append(toIndentedString(solarSystemID)).append("\n");
    sb.append("    solarSystemName: ").append(toIndentedString(solarSystemName)).append("\n");
    sb.append("    stationID: ").append(toIndentedString(stationID)).append("\n");
    sb.append("    activityID: ").append(toIndentedString(activityID)).append("\n");
    sb.append("    blueprintID: ").append(toIndentedString(blueprintID)).append("\n");
    sb.append("    blueprintTypeID: ").append(toIndentedString(blueprintTypeID)).append("\n");
    sb.append("    blueprintTypeName: ").append(toIndentedString(blueprintTypeName)).append("\n");
    sb.append("    blueprintLocationID: ").append(toIndentedString(blueprintLocationID)).append("\n");
    sb.append("    outputLocationID: ").append(toIndentedString(outputLocationID)).append("\n");
    sb.append("    runs: ").append(toIndentedString(runs)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    teamID: ").append(toIndentedString(teamID)).append("\n");
    sb.append("    licensedRuns: ").append(toIndentedString(licensedRuns)).append("\n");
    sb.append("    probability: ").append(toIndentedString(probability)).append("\n");
    sb.append("    productTypeID: ").append(toIndentedString(productTypeID)).append("\n");
    sb.append("    productTypeName: ").append(toIndentedString(productTypeName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timeInSeconds: ").append(toIndentedString(timeInSeconds)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    pauseDate: ").append(toIndentedString(pauseDate)).append("\n");
    sb.append("    completedDate: ").append(toIndentedString(completedDate)).append("\n");
    sb.append("    completedCharacterID: ").append(toIndentedString(completedCharacterID)).append("\n");
    sb.append("    successfulRuns: ").append(toIndentedString(successfulRuns)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("    startDateDate: ").append(toIndentedString(startDateDate)).append("\n");
    sb.append("    endDateDate: ").append(toIndentedString(endDateDate)).append("\n");
    sb.append("    pauseDateDate: ").append(toIndentedString(pauseDateDate)).append("\n");
    sb.append("    completedDateDate: ").append(toIndentedString(completedDateDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

