/*
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class MemberSecurity implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("characterID")
  private Long characterID = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("grantableRoles")
  private List<Long> grantableRoles = new ArrayList<Long>();

  @JsonProperty("grantableRolesAtBase")
  private List<Long> grantableRolesAtBase = new ArrayList<Long>();

  @JsonProperty("grantableRolesAtHQ")
  private List<Long> grantableRolesAtHQ = new ArrayList<Long>();

  @JsonProperty("grantableRolesAtOther")
  private List<Long> grantableRolesAtOther = new ArrayList<Long>();

  @JsonProperty("roles")
  private List<Long> roles = new ArrayList<Long>();

  @JsonProperty("rolesAtBase")
  private List<Long> rolesAtBase = new ArrayList<Long>();

  @JsonProperty("rolesAtHQ")
  private List<Long> rolesAtHQ = new ArrayList<Long>();

  @JsonProperty("rolesAtOther")
  private List<Long> rolesAtOther = new ArrayList<Long>();

  @JsonProperty("titles")
  private List<Long> titles = new ArrayList<Long>();

  @JsonProperty("lifeStartDate")
  private DateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private DateTime lifeEndDate = null;

  public MemberSecurity cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public MemberSecurity eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public MemberSecurity lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public MemberSecurity lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public MemberSecurity characterID(Long characterID) {
    this.characterID = characterID;
    return this;
  }

   /**
   * Get characterID
   * @return characterID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCharacterID() {
    return characterID;
  }

  public void setCharacterID(Long characterID) {
    this.characterID = characterID;
  }

  public MemberSecurity name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MemberSecurity grantableRoles(List<Long> grantableRoles) {
    this.grantableRoles = grantableRoles;
    return this;
  }

  public MemberSecurity addGrantableRolesItem(Long grantableRolesItem) {
    this.grantableRoles.add(grantableRolesItem);
    return this;
  }

   /**
   * Get grantableRoles
   * @return grantableRoles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRoles() {
    return grantableRoles;
  }

  public void setGrantableRoles(List<Long> grantableRoles) {
    this.grantableRoles = grantableRoles;
  }

  public MemberSecurity grantableRolesAtBase(List<Long> grantableRolesAtBase) {
    this.grantableRolesAtBase = grantableRolesAtBase;
    return this;
  }

  public MemberSecurity addGrantableRolesAtBaseItem(Long grantableRolesAtBaseItem) {
    this.grantableRolesAtBase.add(grantableRolesAtBaseItem);
    return this;
  }

   /**
   * Get grantableRolesAtBase
   * @return grantableRolesAtBase
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRolesAtBase() {
    return grantableRolesAtBase;
  }

  public void setGrantableRolesAtBase(List<Long> grantableRolesAtBase) {
    this.grantableRolesAtBase = grantableRolesAtBase;
  }

  public MemberSecurity grantableRolesAtHQ(List<Long> grantableRolesAtHQ) {
    this.grantableRolesAtHQ = grantableRolesAtHQ;
    return this;
  }

  public MemberSecurity addGrantableRolesAtHQItem(Long grantableRolesAtHQItem) {
    this.grantableRolesAtHQ.add(grantableRolesAtHQItem);
    return this;
  }

   /**
   * Get grantableRolesAtHQ
   * @return grantableRolesAtHQ
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRolesAtHQ() {
    return grantableRolesAtHQ;
  }

  public void setGrantableRolesAtHQ(List<Long> grantableRolesAtHQ) {
    this.grantableRolesAtHQ = grantableRolesAtHQ;
  }

  public MemberSecurity grantableRolesAtOther(List<Long> grantableRolesAtOther) {
    this.grantableRolesAtOther = grantableRolesAtOther;
    return this;
  }

  public MemberSecurity addGrantableRolesAtOtherItem(Long grantableRolesAtOtherItem) {
    this.grantableRolesAtOther.add(grantableRolesAtOtherItem);
    return this;
  }

   /**
   * Get grantableRolesAtOther
   * @return grantableRolesAtOther
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getGrantableRolesAtOther() {
    return grantableRolesAtOther;
  }

  public void setGrantableRolesAtOther(List<Long> grantableRolesAtOther) {
    this.grantableRolesAtOther = grantableRolesAtOther;
  }

  public MemberSecurity roles(List<Long> roles) {
    this.roles = roles;
    return this;
  }

  public MemberSecurity addRolesItem(Long rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRoles() {
    return roles;
  }

  public void setRoles(List<Long> roles) {
    this.roles = roles;
  }

  public MemberSecurity rolesAtBase(List<Long> rolesAtBase) {
    this.rolesAtBase = rolesAtBase;
    return this;
  }

  public MemberSecurity addRolesAtBaseItem(Long rolesAtBaseItem) {
    this.rolesAtBase.add(rolesAtBaseItem);
    return this;
  }

   /**
   * Get rolesAtBase
   * @return rolesAtBase
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRolesAtBase() {
    return rolesAtBase;
  }

  public void setRolesAtBase(List<Long> rolesAtBase) {
    this.rolesAtBase = rolesAtBase;
  }

  public MemberSecurity rolesAtHQ(List<Long> rolesAtHQ) {
    this.rolesAtHQ = rolesAtHQ;
    return this;
  }

  public MemberSecurity addRolesAtHQItem(Long rolesAtHQItem) {
    this.rolesAtHQ.add(rolesAtHQItem);
    return this;
  }

   /**
   * Get rolesAtHQ
   * @return rolesAtHQ
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRolesAtHQ() {
    return rolesAtHQ;
  }

  public void setRolesAtHQ(List<Long> rolesAtHQ) {
    this.rolesAtHQ = rolesAtHQ;
  }

  public MemberSecurity rolesAtOther(List<Long> rolesAtOther) {
    this.rolesAtOther = rolesAtOther;
    return this;
  }

  public MemberSecurity addRolesAtOtherItem(Long rolesAtOtherItem) {
    this.rolesAtOther.add(rolesAtOtherItem);
    return this;
  }

   /**
   * Get rolesAtOther
   * @return rolesAtOther
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRolesAtOther() {
    return rolesAtOther;
  }

  public void setRolesAtOther(List<Long> rolesAtOther) {
    this.rolesAtOther = rolesAtOther;
  }

  public MemberSecurity titles(List<Long> titles) {
    this.titles = titles;
    return this;
  }

  public MemberSecurity addTitlesItem(Long titlesItem) {
    this.titles.add(titlesItem);
    return this;
  }

   /**
   * Get titles
   * @return titles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getTitles() {
    return titles;
  }

  public void setTitles(List<Long> titles) {
    this.titles = titles;
  }

  public MemberSecurity lifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public DateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public MemberSecurity lifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public DateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberSecurity memberSecurity = (MemberSecurity) o;
    return Objects.equals(this.cid, memberSecurity.cid) &&
        Objects.equals(this.eveKitVersion, memberSecurity.eveKitVersion) &&
        Objects.equals(this.lifeStart, memberSecurity.lifeStart) &&
        Objects.equals(this.lifeEnd, memberSecurity.lifeEnd) &&
        Objects.equals(this.characterID, memberSecurity.characterID) &&
        Objects.equals(this.name, memberSecurity.name) &&
        Objects.equals(this.grantableRoles, memberSecurity.grantableRoles) &&
        Objects.equals(this.grantableRolesAtBase, memberSecurity.grantableRolesAtBase) &&
        Objects.equals(this.grantableRolesAtHQ, memberSecurity.grantableRolesAtHQ) &&
        Objects.equals(this.grantableRolesAtOther, memberSecurity.grantableRolesAtOther) &&
        Objects.equals(this.roles, memberSecurity.roles) &&
        Objects.equals(this.rolesAtBase, memberSecurity.rolesAtBase) &&
        Objects.equals(this.rolesAtHQ, memberSecurity.rolesAtHQ) &&
        Objects.equals(this.rolesAtOther, memberSecurity.rolesAtOther) &&
        Objects.equals(this.titles, memberSecurity.titles) &&
        Objects.equals(this.lifeStartDate, memberSecurity.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, memberSecurity.lifeEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, characterID, name, grantableRoles, grantableRolesAtBase, grantableRolesAtHQ, grantableRolesAtOther, roles, rolesAtBase, rolesAtHQ, rolesAtOther, titles, lifeStartDate, lifeEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberSecurity {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    characterID: ").append(toIndentedString(characterID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    grantableRoles: ").append(toIndentedString(grantableRoles)).append("\n");
    sb.append("    grantableRolesAtBase: ").append(toIndentedString(grantableRolesAtBase)).append("\n");
    sb.append("    grantableRolesAtHQ: ").append(toIndentedString(grantableRolesAtHQ)).append("\n");
    sb.append("    grantableRolesAtOther: ").append(toIndentedString(grantableRolesAtOther)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    rolesAtBase: ").append(toIndentedString(rolesAtBase)).append("\n");
    sb.append("    rolesAtHQ: ").append(toIndentedString(rolesAtHQ)).append("\n");
    sb.append("    rolesAtOther: ").append(toIndentedString(rolesAtOther)).append("\n");
    sb.append("    titles: ").append(toIndentedString(titles)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

