/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class PlanetaryRoute implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private Long cid;

  public static final String SERIALIZED_NAME_EVE_KIT_VERSION = "eveKitVersion";
  @SerializedName(SERIALIZED_NAME_EVE_KIT_VERSION)
  private Integer eveKitVersion;

  public static final String SERIALIZED_NAME_LIFE_START = "lifeStart";
  @SerializedName(SERIALIZED_NAME_LIFE_START)
  private Long lifeStart;

  public static final String SERIALIZED_NAME_LIFE_END = "lifeEnd";
  @SerializedName(SERIALIZED_NAME_LIFE_END)
  private Long lifeEnd;

  public static final String SERIALIZED_NAME_PLANET_I_D = "planetID";
  @SerializedName(SERIALIZED_NAME_PLANET_I_D)
  private Integer planetID;

  public static final String SERIALIZED_NAME_ROUTE_I_D = "routeID";
  @SerializedName(SERIALIZED_NAME_ROUTE_I_D)
  private Long routeID;

  public static final String SERIALIZED_NAME_SOURCE_PIN_I_D = "sourcePinID";
  @SerializedName(SERIALIZED_NAME_SOURCE_PIN_I_D)
  private Long sourcePinID;

  public static final String SERIALIZED_NAME_DESTINATION_PIN_I_D = "destinationPinID";
  @SerializedName(SERIALIZED_NAME_DESTINATION_PIN_I_D)
  private Long destinationPinID;

  public static final String SERIALIZED_NAME_CONTENT_TYPE_I_D = "contentTypeID";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE_I_D)
  private Integer contentTypeID;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Float quantity;

  public static final String SERIALIZED_NAME_WAYPOINTS = "waypoints";
  @SerializedName(SERIALIZED_NAME_WAYPOINTS)
  private List<Long> waypoints = new ArrayList<>();

  public static final String SERIALIZED_NAME_LIFE_START_DATE = "lifeStartDate";
  @SerializedName(SERIALIZED_NAME_LIFE_START_DATE)
  private OffsetDateTime lifeStartDate;

  public static final String SERIALIZED_NAME_LIFE_END_DATE = "lifeEndDate";
  @SerializedName(SERIALIZED_NAME_LIFE_END_DATE)
  private OffsetDateTime lifeEndDate;

  public PlanetaryRoute cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public PlanetaryRoute eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public PlanetaryRoute lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public PlanetaryRoute lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public PlanetaryRoute planetID(Integer planetID) {
    this.planetID = planetID;
    return this;
  }

   /**
   * Get planetID
   * @return planetID
  **/
  @ApiModelProperty(value = "")
  public Integer getPlanetID() {
    return planetID;
  }

  public void setPlanetID(Integer planetID) {
    this.planetID = planetID;
  }

  public PlanetaryRoute routeID(Long routeID) {
    this.routeID = routeID;
    return this;
  }

   /**
   * Get routeID
   * @return routeID
  **/
  @ApiModelProperty(value = "")
  public Long getRouteID() {
    return routeID;
  }

  public void setRouteID(Long routeID) {
    this.routeID = routeID;
  }

  public PlanetaryRoute sourcePinID(Long sourcePinID) {
    this.sourcePinID = sourcePinID;
    return this;
  }

   /**
   * Get sourcePinID
   * @return sourcePinID
  **/
  @ApiModelProperty(value = "")
  public Long getSourcePinID() {
    return sourcePinID;
  }

  public void setSourcePinID(Long sourcePinID) {
    this.sourcePinID = sourcePinID;
  }

  public PlanetaryRoute destinationPinID(Long destinationPinID) {
    this.destinationPinID = destinationPinID;
    return this;
  }

   /**
   * Get destinationPinID
   * @return destinationPinID
  **/
  @ApiModelProperty(value = "")
  public Long getDestinationPinID() {
    return destinationPinID;
  }

  public void setDestinationPinID(Long destinationPinID) {
    this.destinationPinID = destinationPinID;
  }

  public PlanetaryRoute contentTypeID(Integer contentTypeID) {
    this.contentTypeID = contentTypeID;
    return this;
  }

   /**
   * Get contentTypeID
   * @return contentTypeID
  **/
  @ApiModelProperty(value = "")
  public Integer getContentTypeID() {
    return contentTypeID;
  }

  public void setContentTypeID(Integer contentTypeID) {
    this.contentTypeID = contentTypeID;
  }

  public PlanetaryRoute quantity(Float quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(value = "")
  public Float getQuantity() {
    return quantity;
  }

  public void setQuantity(Float quantity) {
    this.quantity = quantity;
  }

  public PlanetaryRoute waypoints(List<Long> waypoints) {
    this.waypoints = waypoints;
    return this;
  }

  public PlanetaryRoute addWaypointsItem(Long waypointsItem) {
    if (this.waypoints == null) {
      this.waypoints = new ArrayList<>();
    }
    this.waypoints.add(waypointsItem);
    return this;
  }

   /**
   * Get waypoints
   * @return waypoints
  **/
  @ApiModelProperty(value = "")
  public List<Long> getWaypoints() {
    return waypoints;
  }

  public void setWaypoints(List<Long> waypoints) {
    this.waypoints = waypoints;
  }

  public PlanetaryRoute lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public PlanetaryRoute lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanetaryRoute planetaryRoute = (PlanetaryRoute) o;
    return Objects.equals(this.cid, planetaryRoute.cid) &&
        Objects.equals(this.eveKitVersion, planetaryRoute.eveKitVersion) &&
        Objects.equals(this.lifeStart, planetaryRoute.lifeStart) &&
        Objects.equals(this.lifeEnd, planetaryRoute.lifeEnd) &&
        Objects.equals(this.planetID, planetaryRoute.planetID) &&
        Objects.equals(this.routeID, planetaryRoute.routeID) &&
        Objects.equals(this.sourcePinID, planetaryRoute.sourcePinID) &&
        Objects.equals(this.destinationPinID, planetaryRoute.destinationPinID) &&
        Objects.equals(this.contentTypeID, planetaryRoute.contentTypeID) &&
        Objects.equals(this.quantity, planetaryRoute.quantity) &&
        Objects.equals(this.waypoints, planetaryRoute.waypoints) &&
        Objects.equals(this.lifeStartDate, planetaryRoute.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, planetaryRoute.lifeEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, planetID, routeID, sourcePinID, destinationPinID, contentTypeID, quantity, waypoints, lifeStartDate, lifeEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanetaryRoute {\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    planetID: ").append(toIndentedString(planetID)).append("\n");
    sb.append("    routeID: ").append(toIndentedString(routeID)).append("\n");
    sb.append("    sourcePinID: ").append(toIndentedString(sourcePinID)).append("\n");
    sb.append("    destinationPinID: ").append(toIndentedString(destinationPinID)).append("\n");
    sb.append("    contentTypeID: ").append(toIndentedString(contentTypeID)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    waypoints: ").append(toIndentedString(waypoints)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

