/*
 * EveKit Model API Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class ResearchAgent implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private Long cid;

  public static final String SERIALIZED_NAME_EVE_KIT_VERSION = "eveKitVersion";
  @SerializedName(SERIALIZED_NAME_EVE_KIT_VERSION)
  private Integer eveKitVersion;

  public static final String SERIALIZED_NAME_LIFE_START = "lifeStart";
  @SerializedName(SERIALIZED_NAME_LIFE_START)
  private Long lifeStart;

  public static final String SERIALIZED_NAME_LIFE_END = "lifeEnd";
  @SerializedName(SERIALIZED_NAME_LIFE_END)
  private Long lifeEnd;

  public static final String SERIALIZED_NAME_AGENT_I_D = "agentID";
  @SerializedName(SERIALIZED_NAME_AGENT_I_D)
  private Integer agentID;

  public static final String SERIALIZED_NAME_POINTS_PER_DAY = "pointsPerDay";
  @SerializedName(SERIALIZED_NAME_POINTS_PER_DAY)
  private Float pointsPerDay;

  public static final String SERIALIZED_NAME_REMAINDER_POINTS = "remainderPoints";
  @SerializedName(SERIALIZED_NAME_REMAINDER_POINTS)
  private Float remainderPoints;

  public static final String SERIALIZED_NAME_RESEARCH_START_DATE = "researchStartDate";
  @SerializedName(SERIALIZED_NAME_RESEARCH_START_DATE)
  private Long researchStartDate;

  public static final String SERIALIZED_NAME_SKILL_TYPE_I_D = "skillTypeID";
  @SerializedName(SERIALIZED_NAME_SKILL_TYPE_I_D)
  private Integer skillTypeID;

  public static final String SERIALIZED_NAME_LIFE_START_DATE = "lifeStartDate";
  @SerializedName(SERIALIZED_NAME_LIFE_START_DATE)
  private OffsetDateTime lifeStartDate;

  public static final String SERIALIZED_NAME_LIFE_END_DATE = "lifeEndDate";
  @SerializedName(SERIALIZED_NAME_LIFE_END_DATE)
  private OffsetDateTime lifeEndDate;

  public static final String SERIALIZED_NAME_RESEARCH_START_DATE_DATE = "researchStartDateDate";
  @SerializedName(SERIALIZED_NAME_RESEARCH_START_DATE_DATE)
  private OffsetDateTime researchStartDateDate;

  public ResearchAgent cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public ResearchAgent eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public ResearchAgent lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public ResearchAgent lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public ResearchAgent agentID(Integer agentID) {
    this.agentID = agentID;
    return this;
  }

   /**
   * Get agentID
   * @return agentID
  **/
  @ApiModelProperty(value = "")
  public Integer getAgentID() {
    return agentID;
  }

  public void setAgentID(Integer agentID) {
    this.agentID = agentID;
  }

  public ResearchAgent pointsPerDay(Float pointsPerDay) {
    this.pointsPerDay = pointsPerDay;
    return this;
  }

   /**
   * Get pointsPerDay
   * @return pointsPerDay
  **/
  @ApiModelProperty(value = "")
  public Float getPointsPerDay() {
    return pointsPerDay;
  }

  public void setPointsPerDay(Float pointsPerDay) {
    this.pointsPerDay = pointsPerDay;
  }

  public ResearchAgent remainderPoints(Float remainderPoints) {
    this.remainderPoints = remainderPoints;
    return this;
  }

   /**
   * Get remainderPoints
   * @return remainderPoints
  **/
  @ApiModelProperty(value = "")
  public Float getRemainderPoints() {
    return remainderPoints;
  }

  public void setRemainderPoints(Float remainderPoints) {
    this.remainderPoints = remainderPoints;
  }

  public ResearchAgent researchStartDate(Long researchStartDate) {
    this.researchStartDate = researchStartDate;
    return this;
  }

   /**
   * Get researchStartDate
   * @return researchStartDate
  **/
  @ApiModelProperty(value = "")
  public Long getResearchStartDate() {
    return researchStartDate;
  }

  public void setResearchStartDate(Long researchStartDate) {
    this.researchStartDate = researchStartDate;
  }

  public ResearchAgent skillTypeID(Integer skillTypeID) {
    this.skillTypeID = skillTypeID;
    return this;
  }

   /**
   * Get skillTypeID
   * @return skillTypeID
  **/
  @ApiModelProperty(value = "")
  public Integer getSkillTypeID() {
    return skillTypeID;
  }

  public void setSkillTypeID(Integer skillTypeID) {
    this.skillTypeID = skillTypeID;
  }

  public ResearchAgent lifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(value = "lifeStart Date")
  public OffsetDateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(OffsetDateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public ResearchAgent lifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(value = "lifeEnd Date")
  public OffsetDateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(OffsetDateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }

  public ResearchAgent researchStartDateDate(OffsetDateTime researchStartDateDate) {
    this.researchStartDateDate = researchStartDateDate;
    return this;
  }

   /**
   * researchStartDate Date
   * @return researchStartDateDate
  **/
  @ApiModelProperty(value = "researchStartDate Date")
  public OffsetDateTime getResearchStartDateDate() {
    return researchStartDateDate;
  }

  public void setResearchStartDateDate(OffsetDateTime researchStartDateDate) {
    this.researchStartDateDate = researchStartDateDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResearchAgent researchAgent = (ResearchAgent) o;
    return Objects.equals(this.cid, researchAgent.cid) &&
        Objects.equals(this.eveKitVersion, researchAgent.eveKitVersion) &&
        Objects.equals(this.lifeStart, researchAgent.lifeStart) &&
        Objects.equals(this.lifeEnd, researchAgent.lifeEnd) &&
        Objects.equals(this.agentID, researchAgent.agentID) &&
        Objects.equals(this.pointsPerDay, researchAgent.pointsPerDay) &&
        Objects.equals(this.remainderPoints, researchAgent.remainderPoints) &&
        Objects.equals(this.researchStartDate, researchAgent.researchStartDate) &&
        Objects.equals(this.skillTypeID, researchAgent.skillTypeID) &&
        Objects.equals(this.lifeStartDate, researchAgent.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, researchAgent.lifeEndDate) &&
        Objects.equals(this.researchStartDateDate, researchAgent.researchStartDateDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, agentID, pointsPerDay, remainderPoints, researchStartDate, skillTypeID, lifeStartDate, lifeEndDate, researchStartDateDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResearchAgent {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    agentID: ").append(toIndentedString(agentID)).append("\n");
    sb.append("    pointsPerDay: ").append(toIndentedString(pointsPerDay)).append("\n");
    sb.append("    remainderPoints: ").append(toIndentedString(remainderPoints)).append("\n");
    sb.append("    researchStartDate: ").append(toIndentedString(researchStartDate)).append("\n");
    sb.append("    skillTypeID: ").append(toIndentedString(skillTypeID)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("    researchStartDateDate: ").append(toIndentedString(researchStartDateDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

