/*
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package enterprises.orbital.evekit.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;
import java.io.Serializable;

/**
 * Model data common properties
 */
@ApiModel(description = "Model data common properties")

public class Starbase implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("cid")
  private Long cid = null;

  @JsonProperty("eveKitVersion")
  private Integer eveKitVersion = null;

  @JsonProperty("lifeStart")
  private Long lifeStart = null;

  @JsonProperty("lifeEnd")
  private Long lifeEnd = null;

  @JsonProperty("itemID")
  private Long itemID = null;

  @JsonProperty("locationID")
  private Long locationID = null;

  @JsonProperty("moonID")
  private Integer moonID = null;

  @JsonProperty("onlineTimestamp")
  private Long onlineTimestamp = null;

  @JsonProperty("state")
  private Integer state = null;

  @JsonProperty("stateTimestamp")
  private Long stateTimestamp = null;

  @JsonProperty("typeID")
  private Integer typeID = null;

  @JsonProperty("standingOwnerID")
  private Long standingOwnerID = null;

  @JsonProperty("lifeStartDate")
  private DateTime lifeStartDate = null;

  @JsonProperty("lifeEndDate")
  private DateTime lifeEndDate = null;

  @JsonProperty("onlineTimestampDate")
  private DateTime onlineTimestampDate = null;

  @JsonProperty("stateTimestampDate")
  private DateTime stateTimestampDate = null;

  public Starbase cid(Long cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Unique ID
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Unique ID")
  public Long getCid() {
    return cid;
  }

  public void setCid(Long cid) {
    this.cid = cid;
  }

  public Starbase eveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
    return this;
  }

   /**
   * EveKit release version
   * @return eveKitVersion
  **/
  @ApiModelProperty(example = "null", value = "EveKit release version")
  public Integer getEveKitVersion() {
    return eveKitVersion;
  }

  public void setEveKitVersion(Integer eveKitVersion) {
    this.eveKitVersion = eveKitVersion;
  }

  public Starbase lifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
    return this;
  }

   /**
   * Model lifeline start (milliseconds UTC)
   * @return lifeStart
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline start (milliseconds UTC)")
  public Long getLifeStart() {
    return lifeStart;
  }

  public void setLifeStart(Long lifeStart) {
    this.lifeStart = lifeStart;
  }

  public Starbase lifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
    return this;
  }

   /**
   * Model lifeline end (milliseconds UTC), MAX_LONG for live data
   * @return lifeEnd
  **/
  @ApiModelProperty(example = "null", value = "Model lifeline end (milliseconds UTC), MAX_LONG for live data")
  public Long getLifeEnd() {
    return lifeEnd;
  }

  public void setLifeEnd(Long lifeEnd) {
    this.lifeEnd = lifeEnd;
  }

  public Starbase itemID(Long itemID) {
    this.itemID = itemID;
    return this;
  }

   /**
   * Get itemID
   * @return itemID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getItemID() {
    return itemID;
  }

  public void setItemID(Long itemID) {
    this.itemID = itemID;
  }

  public Starbase locationID(Long locationID) {
    this.locationID = locationID;
    return this;
  }

   /**
   * Get locationID
   * @return locationID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLocationID() {
    return locationID;
  }

  public void setLocationID(Long locationID) {
    this.locationID = locationID;
  }

  public Starbase moonID(Integer moonID) {
    this.moonID = moonID;
    return this;
  }

   /**
   * Get moonID
   * @return moonID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMoonID() {
    return moonID;
  }

  public void setMoonID(Integer moonID) {
    this.moonID = moonID;
  }

  public Starbase onlineTimestamp(Long onlineTimestamp) {
    this.onlineTimestamp = onlineTimestamp;
    return this;
  }

   /**
   * Get onlineTimestamp
   * @return onlineTimestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getOnlineTimestamp() {
    return onlineTimestamp;
  }

  public void setOnlineTimestamp(Long onlineTimestamp) {
    this.onlineTimestamp = onlineTimestamp;
  }

  public Starbase state(Integer state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getState() {
    return state;
  }

  public void setState(Integer state) {
    this.state = state;
  }

  public Starbase stateTimestamp(Long stateTimestamp) {
    this.stateTimestamp = stateTimestamp;
    return this;
  }

   /**
   * Get stateTimestamp
   * @return stateTimestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStateTimestamp() {
    return stateTimestamp;
  }

  public void setStateTimestamp(Long stateTimestamp) {
    this.stateTimestamp = stateTimestamp;
  }

  public Starbase typeID(Integer typeID) {
    this.typeID = typeID;
    return this;
  }

   /**
   * Get typeID
   * @return typeID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTypeID() {
    return typeID;
  }

  public void setTypeID(Integer typeID) {
    this.typeID = typeID;
  }

  public Starbase standingOwnerID(Long standingOwnerID) {
    this.standingOwnerID = standingOwnerID;
    return this;
  }

   /**
   * Get standingOwnerID
   * @return standingOwnerID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStandingOwnerID() {
    return standingOwnerID;
  }

  public void setStandingOwnerID(Long standingOwnerID) {
    this.standingOwnerID = standingOwnerID;
  }

  public Starbase lifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
    return this;
  }

   /**
   * lifeStart Date
   * @return lifeStartDate
  **/
  @ApiModelProperty(example = "null", value = "lifeStart Date")
  public DateTime getLifeStartDate() {
    return lifeStartDate;
  }

  public void setLifeStartDate(DateTime lifeStartDate) {
    this.lifeStartDate = lifeStartDate;
  }

  public Starbase lifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
    return this;
  }

   /**
   * lifeEnd Date
   * @return lifeEndDate
  **/
  @ApiModelProperty(example = "null", value = "lifeEnd Date")
  public DateTime getLifeEndDate() {
    return lifeEndDate;
  }

  public void setLifeEndDate(DateTime lifeEndDate) {
    this.lifeEndDate = lifeEndDate;
  }

  public Starbase onlineTimestampDate(DateTime onlineTimestampDate) {
    this.onlineTimestampDate = onlineTimestampDate;
    return this;
  }

   /**
   * onlineTimestamp Date
   * @return onlineTimestampDate
  **/
  @ApiModelProperty(example = "null", value = "onlineTimestamp Date")
  public DateTime getOnlineTimestampDate() {
    return onlineTimestampDate;
  }

  public void setOnlineTimestampDate(DateTime onlineTimestampDate) {
    this.onlineTimestampDate = onlineTimestampDate;
  }

  public Starbase stateTimestampDate(DateTime stateTimestampDate) {
    this.stateTimestampDate = stateTimestampDate;
    return this;
  }

   /**
   * stateTimestamp Date
   * @return stateTimestampDate
  **/
  @ApiModelProperty(example = "null", value = "stateTimestamp Date")
  public DateTime getStateTimestampDate() {
    return stateTimestampDate;
  }

  public void setStateTimestampDate(DateTime stateTimestampDate) {
    this.stateTimestampDate = stateTimestampDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Starbase starbase = (Starbase) o;
    return Objects.equals(this.cid, starbase.cid) &&
        Objects.equals(this.eveKitVersion, starbase.eveKitVersion) &&
        Objects.equals(this.lifeStart, starbase.lifeStart) &&
        Objects.equals(this.lifeEnd, starbase.lifeEnd) &&
        Objects.equals(this.itemID, starbase.itemID) &&
        Objects.equals(this.locationID, starbase.locationID) &&
        Objects.equals(this.moonID, starbase.moonID) &&
        Objects.equals(this.onlineTimestamp, starbase.onlineTimestamp) &&
        Objects.equals(this.state, starbase.state) &&
        Objects.equals(this.stateTimestamp, starbase.stateTimestamp) &&
        Objects.equals(this.typeID, starbase.typeID) &&
        Objects.equals(this.standingOwnerID, starbase.standingOwnerID) &&
        Objects.equals(this.lifeStartDate, starbase.lifeStartDate) &&
        Objects.equals(this.lifeEndDate, starbase.lifeEndDate) &&
        Objects.equals(this.onlineTimestampDate, starbase.onlineTimestampDate) &&
        Objects.equals(this.stateTimestampDate, starbase.stateTimestampDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, eveKitVersion, lifeStart, lifeEnd, itemID, locationID, moonID, onlineTimestamp, state, stateTimestamp, typeID, standingOwnerID, lifeStartDate, lifeEndDate, onlineTimestampDate, stateTimestampDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Starbase {\n");
    
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    eveKitVersion: ").append(toIndentedString(eveKitVersion)).append("\n");
    sb.append("    lifeStart: ").append(toIndentedString(lifeStart)).append("\n");
    sb.append("    lifeEnd: ").append(toIndentedString(lifeEnd)).append("\n");
    sb.append("    itemID: ").append(toIndentedString(itemID)).append("\n");
    sb.append("    locationID: ").append(toIndentedString(locationID)).append("\n");
    sb.append("    moonID: ").append(toIndentedString(moonID)).append("\n");
    sb.append("    onlineTimestamp: ").append(toIndentedString(onlineTimestamp)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    stateTimestamp: ").append(toIndentedString(stateTimestamp)).append("\n");
    sb.append("    typeID: ").append(toIndentedString(typeID)).append("\n");
    sb.append("    standingOwnerID: ").append(toIndentedString(standingOwnerID)).append("\n");
    sb.append("    lifeStartDate: ").append(toIndentedString(lifeStartDate)).append("\n");
    sb.append("    lifeEndDate: ").append(toIndentedString(lifeEndDate)).append("\n");
    sb.append("    onlineTimestampDate: ").append(toIndentedString(onlineTimestampDate)).append("\n");
    sb.append("    stateTimestampDate: ").append(toIndentedString(stateTimestampDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

